export {default as SignIn} from "./signIn"
export {default as Signup} from "./signUp"
export {default as Home} from "./home"
export {default as Quizes} from "./quizes"
export {default as QuizDetails}from "./qDetails"
export {default as Videos}from "./videos"
export {default as Summaries}from "./summaries"
export {default as PicDetails}from "./picDetails"
export {default as Profile}from "./profile"